I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/transforms.rpy", line 180, in script
    return
Exception: Could not find return label (u'game/day-1.rpy', 1640191750, 9).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/transforms.rpy", line 180, in script
    return
  File "renpy/ast.py", line 1562, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "renpy/execution.py", line 710, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'game/day-1.rpy', 1640191750, 9).

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
And So, I Fall 1.0
Sat Feb  5 20:25:59 2022
