I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day-1.rpy", line 412, in script
    scene kitchen bg # TODO: Fix this!
Exception: Image 'kitchen' does not accept attributes 'bg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day-1.rpy", line 412, in script
    scene kitchen bg # TODO: Fix this!
  File "renpy/ast.py", line 1323, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1162, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 744, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/core.py", line 390, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'kitchen' does not accept attributes 'bg'.

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
Solstice 1.0
Wed Dec 15 20:59:51 2021
